import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { z } from "zod";

const isoDateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const timeSchema = z.string().regex(/^\d{2}:\d{2}$/);

const eventSchema = z.object({
  titleNe: z.string().min(1),
  titleEn: z.string().optional(),
  eventType: z
    .enum(["holiday", "festival", "observance", "fasting", "custom"])
    .default("festival"),
  isPublicHoliday: z.boolean().default(false),
  isOptionalHoliday: z.boolean().default(false),
  metadata: z.record(z.string(), z.unknown()).optional(),
});

const daySchema = z.object({
  adDate: isoDateSchema,
  bsYear: z.number().int().min(1900).max(2200),
  bsMonth: z.number().int().min(1).max(12),
  bsDay: z.number().int().min(1).max(32),
  bsMonthNameNe: z.string().min(1),
  bsMonthNameEn: z.string().min(1),
  weekdayIndex: z.number().int().min(0).max(6),
  weekdayNameNe: z.string().min(1),
  weekdayNameEn: z.string().min(1),
  tithi: z.string().optional(),
  paksha: z.string().optional(),
  lunarMonthNe: z.string().optional(),
  lunarMonthEn: z.string().optional(),
  nakshatra: z.string().optional(),
  yoga: z.string().optional(),
  karana: z.string().optional(),
  sunrise: timeSchema.optional(),
  sunset: timeSchema.optional(),
  moonrise: timeSchema.optional(),
  moonset: timeSchema.optional(),
  isWeekend: z.boolean().default(false),
  notes: z.string().optional(),
  events: z.array(eventSchema).default([]),
});

const datasetSchema = z
  .object({
    version: z.number().int().default(1),
    generatedAt: z.string().optional(),
    days: z.array(daySchema).min(1),
  })
  .superRefine((value, ctx) => {
    const adDateSet = new Set<string>();
    const bsDateSet = new Set<string>();

    value.days.forEach((day, index) => {
      const bsDate = `${day.bsYear}-${String(day.bsMonth).padStart(2, "0")}-${String(
        day.bsDay
      ).padStart(2, "0")}`;

      if (adDateSet.has(day.adDate)) {
        ctx.addIssue({
          code: "custom",
          path: ["days", index, "adDate"],
          message: `Duplicate adDate: ${day.adDate}`,
        });
      }

      if (bsDateSet.has(bsDate)) {
        ctx.addIssue({
          code: "custom",
          path: ["days", index],
          message: `Duplicate BS date: ${bsDate}`,
        });
      }

      adDateSet.add(day.adDate);
      bsDateSet.add(bsDate);
    });
  });

function getArgValue(flag: string, fallback: string) {
  const args = process.argv.slice(2);
  const flagIndex = args.indexOf(flag);

  if (flagIndex >= 0 && args[flagIndex + 1]) {
    return args[flagIndex + 1];
  }

  return fallback;
}

function escapeSql(input: string) {
  return input.replaceAll("'", "''");
}

function textSql(value: string | undefined) {
  if (!value) {
    return "NULL";
  }

  return `'${escapeSql(value)}'`;
}

function boolSql(value: boolean) {
  return value ? "1" : "0";
}

const inputPath = resolve(getArgValue("--input", "data/nepali-calendar.seed.json"));
const outputPath = resolve(getArgValue("--output", "drizzle/seed/calendar-seed.sql"));

const raw = await readFile(inputPath, "utf-8");
const parsed = datasetSchema.parse(JSON.parse(raw));

const sqlLines: string[] = [
  "-- Auto-generated by scripts/seed-nepali-calendar.ts",
  "-- Input format version: 1",
  "PRAGMA foreign_keys = ON;",
  [
    "CREATE TABLE IF NOT EXISTS calendar_day (",
    "  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,",
    "  ad_date TEXT NOT NULL,",
    "  bs_date TEXT NOT NULL,",
    "  bs_year INTEGER NOT NULL,",
    "  bs_month INTEGER NOT NULL,",
    "  bs_day INTEGER NOT NULL,",
    "  bs_month_name_ne TEXT NOT NULL,",
    "  bs_month_name_en TEXT NOT NULL,",
    "  weekday_index INTEGER NOT NULL,",
    "  weekday_name_ne TEXT NOT NULL,",
    "  weekday_name_en TEXT NOT NULL,",
    "  tithi TEXT,",
    "  paksha TEXT,",
    "  lunar_month_ne TEXT,",
    "  lunar_month_en TEXT,",
    "  nakshatra TEXT,",
    "  yoga TEXT,",
    "  karana TEXT,",
    "  sunrise TEXT,",
    "  sunset TEXT,",
    "  moonrise TEXT,",
    "  moonset TEXT,",
    "  is_weekend INTEGER DEFAULT false NOT NULL,",
    "  notes TEXT,",
    "  created_at INTEGER DEFAULT (unixepoch() * 1000) NOT NULL,",
    "  updated_at INTEGER DEFAULT (unixepoch() * 1000) NOT NULL",
    ");",
    "CREATE UNIQUE INDEX IF NOT EXISTS calendar_day_ad_date_idx ON calendar_day (ad_date);",
    "CREATE UNIQUE INDEX IF NOT EXISTS calendar_day_bs_date_idx ON calendar_day (bs_date);",
  ].join("\n"),
  [
    "CREATE TABLE IF NOT EXISTS calendar_event (",
    "  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,",
    "  day_id INTEGER NOT NULL,",
    "  title_ne TEXT NOT NULL,",
    "  title_en TEXT,",
    "  event_type TEXT DEFAULT 'festival' NOT NULL,",
    "  is_public_holiday INTEGER DEFAULT false NOT NULL,",
    "  is_optional_holiday INTEGER DEFAULT false NOT NULL,",
    "  metadata TEXT,",
    "  created_at INTEGER DEFAULT (unixepoch() * 1000) NOT NULL,",
    "  FOREIGN KEY (day_id) REFERENCES calendar_day(id) ON UPDATE no action ON DELETE cascade",
    ");",
    "CREATE UNIQUE INDEX IF NOT EXISTS calendar_event_day_type_title_idx ON calendar_event (day_id, event_type, title_ne);",
  ].join("\n"),
  "BEGIN TRANSACTION;",
];

for (const day of parsed.days) {
  const bsDate = `${day.bsYear}-${String(day.bsMonth).padStart(2, "0")}-${String(
    day.bsDay
  ).padStart(2, "0")}`;

  sqlLines.push(
    [
      "INSERT INTO calendar_day (",
      "  ad_date, bs_date, bs_year, bs_month, bs_day, bs_month_name_ne, bs_month_name_en,",
      "  weekday_index, weekday_name_ne, weekday_name_en,",
      "  tithi, paksha, lunar_month_ne, lunar_month_en, nakshatra, yoga, karana,",
      "  sunrise, sunset, moonrise, moonset, is_weekend, notes",
      ") VALUES (",
      `  ${textSql(day.adDate)}, ${textSql(bsDate)}, ${day.bsYear}, ${day.bsMonth}, ${day.bsDay}, ${textSql(
        day.bsMonthNameNe
      )}, ${textSql(day.bsMonthNameEn)},`,
      `  ${day.weekdayIndex}, ${textSql(day.weekdayNameNe)}, ${textSql(day.weekdayNameEn)},`,
      `  ${textSql(day.tithi)}, ${textSql(day.paksha)}, ${textSql(day.lunarMonthNe)}, ${textSql(
        day.lunarMonthEn
      )}, ${textSql(day.nakshatra)}, ${textSql(day.yoga)}, ${textSql(day.karana)},`,
      `  ${textSql(day.sunrise)}, ${textSql(day.sunset)}, ${textSql(day.moonrise)}, ${textSql(
        day.moonset
      )}, ${boolSql(day.isWeekend)}, ${textSql(day.notes)}`,
      ")",
      "ON CONFLICT(ad_date) DO UPDATE SET",
      "  bs_date = excluded.bs_date,",
      "  bs_year = excluded.bs_year,",
      "  bs_month = excluded.bs_month,",
      "  bs_day = excluded.bs_day,",
      "  bs_month_name_ne = excluded.bs_month_name_ne,",
      "  bs_month_name_en = excluded.bs_month_name_en,",
      "  weekday_index = excluded.weekday_index,",
      "  weekday_name_ne = excluded.weekday_name_ne,",
      "  weekday_name_en = excluded.weekday_name_en,",
      "  tithi = excluded.tithi,",
      "  paksha = excluded.paksha,",
      "  lunar_month_ne = excluded.lunar_month_ne,",
      "  lunar_month_en = excluded.lunar_month_en,",
      "  nakshatra = excluded.nakshatra,",
      "  yoga = excluded.yoga,",
      "  karana = excluded.karana,",
      "  sunrise = excluded.sunrise,",
      "  sunset = excluded.sunset,",
      "  moonrise = excluded.moonrise,",
      "  moonset = excluded.moonset,",
      "  is_weekend = excluded.is_weekend,",
      "  notes = excluded.notes,",
      "  updated_at = (unixepoch() * 1000);",
    ].join("\n")
  );

  sqlLines.push(
    `DELETE FROM calendar_event WHERE day_id = (SELECT id FROM calendar_day WHERE ad_date = ${textSql(
      day.adDate
    )});`
  );

  for (const event of day.events) {
    sqlLines.push(
      [
        "INSERT INTO calendar_event (",
        "  day_id, title_ne, title_en, event_type, is_public_holiday, is_optional_holiday, metadata",
        ") SELECT",
        `  id, ${textSql(event.titleNe)}, ${textSql(event.titleEn)}, ${textSql(
          event.eventType
        )}, ${boolSql(event.isPublicHoliday)}, ${boolSql(
          event.isOptionalHoliday
        )}, ${textSql(event.metadata ? JSON.stringify(event.metadata) : undefined)}`,
        `FROM calendar_day WHERE ad_date = ${textSql(day.adDate)};`,
      ].join("\n")
    );
  }
}

sqlLines.push("COMMIT;");

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${sqlLines.join("\n\n")}\n`, "utf-8");

console.log(
  `Seed SQL generated for ${parsed.days.length} calendar days:\n- input: ${inputPath}\n- output: ${outputPath}`
);
